kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: app-1-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
- role: worker
  image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
  extraPortMappings:
   - containerPort: 30053 # expose CoreDNS port to port 53 on the host machine
     hostPort: 53
     protocol: udp
   - containerPort: 30053 # expose CoreDNS port to port 53 on the host machine
     hostPort: 53
     protocol: tcp
networking:
  apiServerAddress: "192.168.56.15"
  apiServerPort: 58350
